spring:
  datasource:
    url: jdbc:postgresql://db:5432/restaurante_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

server:
  port: 8080